### ISSUE TITLE
ciao: Add support for dual (network and compute) launcher mode

### ISSUE THREAD

**Issue by obedmr** [clearlinux/clear-config-management#64]

**Comment by albertomurillo** [comment]
There are some approaches to this.

1) Create a new ciao-launcher role. with two variables is_compute_node and is_network_node set to False by default, then the user has to call the role like this.

```
- hosts: computes
   vars:
     is_compute_node: true
   roles:
     - clearlinux.ciao-launcher

- hosts: networks
   vars:
     is_network_node: true
   roles:
     - clearlinux.ciao-launcher
```

Or to deploy in the same host.

```
- hosts: localhost
   vars:
     is_network_node: true
     is_compute_node: true
   roles:
     - clearlinux.ciao-launcher
```
